### ISSUE TITLE
Error in npm install

### ISSUE THREAD

**Issue by linck** [devfreebooks/devfreebooks.github.io#1]
Hi @caio-ribeiro-pereira.
I have a problem in npm install, specifically in grunt-harp install:

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\beto_\AppData\Roaming\nvm\v6.9.1\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\beto_\\AppData\\Roaming\\nvm\\v6.9.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Dev\Projetos\devfreeebooks\node_modules\grunt-harp\node_modules\harp\node_modules\terraform\node_modules\node-sass
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
devfreebooks@1.0.0 D:\Dev\Projetos\devfreeebooks
`-- (empty)

npm WARN devfreebooks@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.3 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@0.9.3 install script 'node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Dev\Projetos\devfreeebooks\npm-debug.log
npm ERR! code 1
```

**Comment by caio-ribeiro-pereira** [comment]
hi @linck it only works on node 0.12 yet.

But if you wanna add some books, just send a PR following theses rules (https://github.com/devfreebooks/devfreebooks.github.io#how-to-add-books) because there is no need to install and run locally.

**Comment by linck** [comment]
Ok @caio-ribeiro-pereira. Thanks!
